name: Node.js CI/CD & Terraform Apply

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy infrastructure'
        required: true
        default: false
        type: boolean

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm test
    - name: Upload dist directory
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  terraform-deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./_iac
    env:
      TF_VAR_environment: dev
      TF_VAR_app_version: 1.0.0
    if: github.event.inputs.destroy == false
    steps:
    - uses: actions/checkout@v3
    - name: Download dist directory
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Terraform Init
      run: terraform init -backend-config="backend-config/dev.tf"
      
    - name: Terraform Plan
      run: terraform plan
      
    - name: Terraform Apply
      run: terraform apply --auto-approve
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./_iac
    env:
      TF_VAR_environment: dev
      TF_VAR_app_version: 1.0.0
    if: github.event.inputs.destroy == true

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Terraform Init
      run: terraform init -backend-config="backend-config/dev.tf"

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=tfplan

    - name: Terraform Destroy
      run: terraform apply -auto-approve tfplan