name: AWS Lambda serverless Pipeline
on:
    push: 
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
            - uses: actions/checkout@v3
            - name: Setup Node.js
            - uses: actions/setup-node@v3
             with: 
                node-version: 18.X
            - name: Install Dependencies
            - run: npm install
            - name: Lint the App
            - run: npm run lint
            - name: Build the App
            - run: npm run build
    test:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/node-latest@v3
            - name: Run the test cases
            - run: npm run test
            
  